--○ 실습 테이블 생성
CREATE TABLE TBL_SCORE
( SID   NUMBER
, NAME  VARCHAR2(30)
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
);
--==>>Table TBL_SCORE이(가) 생성되었습니다.

--○ 제약조건 추가(SID 컬럼에 PK 제약조건 추가)
ALTER TABLE TBL_SCORE 
ADD CONSTRAINT TBL_SCORE_SID_PK PRIMARY KEY(SID);
--==>>Table TBL_SCORE이(가) 변경되었습니다.

--○ 제약 조건 추가 (KOR,ENG,MAT컬럼에 CK제약조건 추가)
ALTER TABLE TBL_SCORE
ADD ( CONSTRAINT TBL_SCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
    , CONSTRAINT TBL_SCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
    , CONSTRAINT TBL_SCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100) );
--==>>Table TBL_SCORE이(가) 변경되었습니다.

--○ 시퀀스 생성
CREATE SEQUENCE SCORESEQ
NOCACHE;
--==>>Sequence SCORESEQ이(가) 생성되었습니다.

INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '%s','%s','%s','%s')
;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT)"총점", (KOR+ENG+MAT)/3"평균"
FROM TBL_SCORE
ORDER BY 1 ASC; 


SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT)"총점", (KOR+ENG+MAT)/3"평균" FROM TBL_SCORE ORDER BY 1 ASC
;

SELECT COUNT(*)
FROM TBL_SCORE;

SELECT COUNT(*) FROM TBL_SCORE
;

TRUNCATE TABLE TBL_SCORE;

DROP SEQUENCE SCORESEQ;